server:
  # 服务器模式: 'openai' (标准兼容) 或 'queue' (流式队列)
  type: queue
  # 监听端口
  port: 3000
  # 鉴权密钥 (Bearer Token)，请使用 genapikey.js 生成
  auth: sk-change-me-to-your-secure-key

chrome:
  # 浏览器可执行文件路径 (留空则使用Puppeteer默认)
  # Windows系统示例 "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
  # Linux系统示例 "/usr/bin/chromium"
  path: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
  # 是否启用无头模式
  headless: false
  # 是否启用 GPU (无GPU设备运行请使用false)
  gpu: false
  # 代理设置
  proxy:
    # 是否启用代理
    enable: false
    # 代理类型: 'http' 或 'socks5'
    type: http
    # 代理服务器地址
    host: 127.0.0.1
    # 代理端口
    port: 7890
    # 代理认证 (可选)
    # user: username
    # passwd: password
